### ISSUE TITLE
[Docs] TranslationFest

### ISSUE THREAD

**Issue by rogeriopradoj** [PHPSP/hexagon-project#13]
Depois do TestFest, que tal um TranslationFest?

PHPSP + Docs : TranslationFest? PHPSP + TranslationFest? PHPSP + #### :-)

Conversei com o @klaussilveira no InterCon PHP, ele falou que poderia ser mentor de um evento desse tipo focado na documentação/manual do PHP, só combinarmos novamente uma data, e conseguirmos um lugar para o evento rolar.
# 

Em setembro de 2013 já fizemos um, https://credencial.imasters.com.br/phpsp-docs-1. Quem sabe fazemos um maior agora? Quem topa?

**Comment by adlermedrado** [comment]
Olá PHPSP/hexagon-project,
Uma mensagem de Adler Medrado foi deixada no IQ Elite para você. 
Clique aqui a.iqelite.com/j/Sg5JAb/8n3/?hg=knK0J4X2zt para ler a sua mensagem 


A Equipe do IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=0e6999b0&email=reply@reply.github.com.&hg=knK0J4X2zt IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by adlermedrado** [comment]
Olá,

adlermedrado  começou a usar IQ Elite. Ele escreveu-lhe uma mensagem. 

Para ler a mensagem antes de expirar, basta clicar neste link: a.iqelite.com/entry/new_message/2a9bef6c620fdc5bf20a9bf0ac2d3fda9e1f544b80bfb/320c612f7502e51515160a85f6ecb517cbebd7491bd897459c467a9c5c5b67cb7cb83bec4519059a87b59af667b747ca852cb516d90519060b7cb515151515151515858518959c47466909060a8587b91b7c4515f6d895867bebdc320c612f75044d3e22edb35af44b80bfb/?hg=yuqom6a8cz

Leia a sua mensagem antes que expire!            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=0e6999b0&email=reply@reply.github.com.&hg=yuqom6a8cz IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------

**Comment by adlermedrado** [comment]
Olá,

O seu amigo(a) adlermedrado enviou-lhe uma mensagem há 36h dias, e que ainda não foi lida.

Dentro de 24 horas a mensagem será apagada.

Se você tem curiosidade em saber o que adlermedrado escreveu, clique aqui: a.iqelite.com/entry/new_message/2a9bef6c620fdc5bf20a9bf0ac2d3fda9e1f544b80bfb/320c612f7502e51515160a85f6ecb517cbebd7491bd897459c467a9c5c5b67cb7cb83bec4519059a87b59af667b747ca852cb516d90519060b7cb515151515151515858518959c47466909060a8587b91b7c4515f6d895867bebdc320c612f75044d3e22edb35af44b80bfb/?hg=SOcBgtl6yb            

Atenciosamente, 
 Equipe IQ Elite



---------------------------------------------------------------------------
Esta mensagem foi enviada para reply@reply.github.com. Se não quiser continuar recebendo estes emails de IQ Elite, clique por favor neste link: a.iqelite.com/common/unsubscribe/?code=0e6999b0&email=reply@reply.github.com.&hg=SOcBgtl6yb IQ Elite é um serviço com sede principal em: C/ Gran De Gràcia 15, 2a 1a, 08012 Barcelona, Espanha.
---------------------------------------------------------------------------
