### ISSUE TITLE
[Site] Plugin WordPress para o Meetup

### ISSUE THREAD

**Issue by duodraco** [PHPSP/hexagon-project#3]
Criar (ou contribuir com) um plugin de worpress, que possamos usar no nosso site integrado com o calendário do Meetup. Vale também criar uma página calendário

**Comment by jpjoao** [comment]
Quais são as reais necessidades? Tem uma infinidade de plugins que poderiam ser usados. Se queremos apenas mostrar os eventos que estão vindo (substituir a imagem na primeira coluna do site) acredito que esse plugin seria o suficiente (e rápido de ser integrado): https://wordpress.org/plugins/meetup-widgets/screenshots/

**Comment by pauloelr** [comment]
@jpjoao é isso mesmo

É que na época que criamos essa issue o meetup estava começando a fazer sucesso então ainda não tinha nenhum plugin aceitavelmente decente.... agora provavelmente já tem inclusive muitos outros além do que você citou.

Então realmente agora não tem mesmo mais necessidade de fazer um.... seria só pegar um pronto mesmo

**Comment by jpjoao** [comment]
PR criado para instalar o plugin mencionado: https://github.com/PHPSP/phpsp-blog-theme/pull/24
