### ISSUE TITLE
[site] Datas estão em inglês

### ISSUE THREAD

**Issue by jpjoao** [PHPSP/hexagon-project#33]
As datas nas páginas de arquivo e post estão em inglês. Deveriam estar em Português.

**Comment by pauloelr** [comment]
Realmente é uma configuração no administrativo
Porem ao tentar corrigir eu encontrei outro problema com encoding:

![untitled](https://cloud.githubusercontent.com/assets/1790910/6694423/0857c244-ccb9-11e4-8718-58130efa2346.png)

Tentei trocar manualmente o enconding pra ver se algum funcionava mas não tive sucesso, por isso voltei a configuração para inglês

**Comment by jpjoao** [comment]
Importei o dump do banco de producao e mudei para portugues a data. Nao consegui reproduzir o erro.

![selection_037](https://cloud.githubusercontent.com/assets/3832326/6697159/a4b65452-cce6-11e4-94c8-eb5a8f8d48ff.png)

Alguem vai tentar debugar e tentar resolver isso ou eu dou alguma atencao a isso?
(ou ainda, a solucao mais porca, mudamos para data no formato DD/MM/YYYY e pronto, fim da crise com acentos na data)

**Comment by pauloelr** [comment]
Oi,

Então muito provavelmente o problema é com o encoding do banco.
Quando você subiu no seu ambiente de dev deve ter subido em um banco com outro encoding
Acho melhor então deixar no formato DD/MM/YYYY assim já corrige isso e evita problema futuros

**Comment by jpjoao** [comment]
A idéia aqui é alterar todos os templates para usar o formato de data que estiver configurado no admin do wordpress (como deveria ser) e não hardcoded (como esta).
Assim, quando o DB for corrigido as datas podem ser novamente exibidas no formato por extenso.
