### ISSUE TITLE
Como membro da comunidade quero ter a opção de auto-invite ativa no Slack

### ISSUE THREAD

**Issue by jpjoao** [PHPSP/hexagon-project#36]
Para facilitar o acesso de novos membros devemos ativar o auto-invite de usuários no Slack e ter uma página descritiva de como proceder no site.

**Comment by royopa** [comment]
+1

**Comment by ghost** [comment]
+1

@brunoric

**Comment by rogeriopradoj** [comment]
+1 @rogeriopradoj. Acho que o http://rauchg.com/slackin/ é uma opção, não? O pessoal do http://docker-br.herokuapp.com/ está usando!

**Comment by augustohp** [comment]
Dahora isso ae hein!

**Comment by jpjoao** [comment]
Falaram também de uma opção que o pessoal de Laravel ta usando.

E tem também um que citei no próprio slack hoje: https://github.com/outsideris/slack-invite-automation

Mas, dependendo da dificuldade, pq não fazer um open source em PHP? =)

**Comment by rogeriopradoj** [comment]
@augustohp e @diegocpires , vocês que estão comandando o Heroku que tem o dumbo, não?

Acham que rola colocar um desses autoinvites lá no mesmo lugar?

**Comment by augustohp** [comment]
Vou ver. Mas acho que o dumbo sendo usado não é o meu. Viu ver mesmo assim.

**Comment by jpjoao** [comment]
Feito: 
Fiz um fork da implementação em node em https://github.com/jpjoao/slackin e traduzi o que dava pra português e coloquei a cor no badge em azul. Subi no Heroku:
http://slaking-phpsp.herokuapp.com/
![badge php-sp](http://slaking-phpsp.herokuapp.com/badge.svg)

Estou agora vendo como colocar no site, via iframe, a tela de cadastro e/ou o badge/badge com inscrição.

Mais em breve.
